<?php echo $this->partial('playground-game/partial/scripts', array('game'=>$this->game, 'channel' => $this->channel));?>
<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->frontendUrl(''. $this->game->getClassType() . '/play', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel)));
?>

<?php $totalQuestions = count($this->questions);?>
<?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game, 'channel' => $this->channel));?>
<!-- GAME QUIZ - FERME QUESTIONS -->
<div id="zone_perso" class="game-postvote play wrap-game">
    <h2 class="full"><?php echo $this->translate('2. Votre Alfie') // TODO echo $form->title?></h2>
	<!-- Content -->
	<div id="content-article" class="content-game clearfix">
        <div class="col-md-12">
            <?php echo $this->game->getForm()->getDescription(); ?>
        </div>
        <div class="row">
            <div class="col-md-6">
                <h1><?php echo $this->translate('Comment </br>prendre votre Alfie ?')?></h1>
                <p class="explications">
                    C’est très simple : </br>
                    prenez vous en photo 
                    (type « Portrait ») 
                    avec un élément distinctif 
                    de Alfa Romeo.</br></br>
                </p>
                <p class="explications">Exemple :</p>
            </div>
            <div class="col-md-6">
                <img src="<?php echo $this->frontendAssetPath('alfie/images/alfie_exemple.jpg'); ?>" alt="" />
            </div>
        </div>
	</div>
</div>
<div class="page col-md-12 clearfix">
            <?php
            echo $this->form()->openTag($form);
            foreach ($this->form as $element) :
                $attributes = $element->getAttributes();
                $required = $attributes['required'];
                $element->setAttributes(array('class' => 'form-control'));
                $requiredContent = '';
                (!empty($required)) ? $requiredContent = '<span class="text-error">*</span>' : '';
                if ($element instanceof Zend\Form\Element\Text) : ?>
                    <div class="form-group clearfix">
                         <label class="col-md-5">
                            <?php echo ($element->getLabel())? $this->formLabel($element) . ' ' . $requiredContent : ''; ?>
                         </label>
                         <div class="col-md-7">
                            <?php echo $this->formText($element) ?>
                            <?php echo $this->formElementErrors($element) ?>
                         </div>
                    </div>
                <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
                    <div class="form-group clearfix">
                        <label class="col-md-5">
                            <?php echo ($element->getLabel()) ? $this->formLabel($element) . ' ' . $requiredContent : ''; ?>
                        </label>
                        <div class="col-md-7">
                            <?php
                            echo $this->formTextarea($element);
                            ?>
                            <?php echo $this->formElementErrors($element) ?>
                        </div>
                       <div class="text-right col-md-11">
                           <span class="character-left"></span> 
                           <?php echo $this->translate('remaining characters'); ?>
                       </div>
                     </div>
                <?php elseif ($element instanceof Zend\Form\Element\File): ?>
                    <div class="photo-file form-group clearfix" data-url="<?php echo $this->frontendUrl(''. $this->game->getClassType() . '/play/ajaxupload', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>" data-canonical="<?php echo $this->url('frontend', array('channel' => $this->channel), array('force_canonical' => true)) ?>">
                        <!-- <label class="col-md-5">
                            <?php echo ($element->getLabel()) ? $this->formLabel($element) . ' ' . $requiredContent :''; ?>
                            <br/>
                            <span class="annotation">
                                500ko maximum
                            </span>
                        </label> -->
                        <div>
                            <div class="preview-img">
                            <?php if (false) : // if($element->getValue() != ''):?>
                                <img class="preview" src="<?php echo $this->basePath($element->getValue());?>"/>
                                <a href="#"
                                    class="trash"
                                    data-delete="<?php echo $this->frontendUrl(''. $this->game->getClassType() . '/play/ajaxdelete', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel))?>"
                                    data-name="<?php echo $element->getName() ?>">
                                    <img src="<?php echo $this->frontendAssetPath('images/common/trash.png');?>" alt="Supprimer" />
                                </a>
                            <?php endif;?>
                            </div>
                        </div>

                        <div class="upload">
                            <?php echo $this->formFile($element); ?>
                            <label for="upload" class="button"><?php echo $this->translate('Réaliser mon Alfie'); ?></label>
                            <?php echo $this->formElementErrors($element) ?>
                        </div>
                    </div>
                <?php endif;?>
            <?php endforeach;?> 
        
        
            <?php echo $this->form()->closeTag() ?>
        </div>
<!-- END GAME QUIZ - FERME QUESTIONS-->
<?php echo $this->partial('playground-game/partial/game-footer', array('game'=>$this->game, 'channel' => $this->channel));?>
<script>
$('#upload_alfie').on('change', function() {
	$(this).parents('form').submit();
});
</script>

<!-- Sophus3 tag starts-->
<script type="text/javascript" language="JavaScript">
s3_page_alias="/promo/alfie/keepmeinformed/photo_tutorial/";
$('#upload_alfie').on('click', function() {
	s3_log('/promo/alfie/keepmeinformed/photo_capture/');
});
</script>
<!-- Sophus3 tag ends-->
