<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame'); ?>
<?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game, 'channel' => $this->channel));?>
<?php echo $this->partial('playground-game/partial/scripts', array('game'=>$this->game, 'channel' => $this->channel));?>

<?php
$form = $this->form;
$form->prepare();
//$form->setAttribute('action', $this->url('frontend/'. $this->game->getClassType() . '/register', array('id' => $this->game->getIdentifier(), 'channel' => $this->channel)));
?>

<div id="zone_perso">
    <h2 class="full"><?php echo $this->translate('1. Vos coordonnées') // TODO echo $form->title?></h2>
    <?php
    echo $this->form()->openTag($form);
    foreach ($this->form as $element) :
        $attributes = $element->getAttributes();
        $required = $attributes['required'];
        $element->setAttributes(array('class' => 'form-control'));
        $requiredContent = '';
        (!empty($required)) ? $requiredContent = '<span class="text-error">*</span>' : '';
        if ($element instanceof Zend\Form\Element\Text) : ?>
            <div class="row clearfix">
                 <?php //echo ($element->getLabel())? $this->formLabel($element) . ' ' . $requiredContent : ''; ?>
                <div class="col-md-7">
                    <?php echo $this->formText($element) ?>
                    <?php echo $this->formElementErrors($element) ?>

                </div>
            </div>
        <?php elseif ($element instanceof Zend\Form\Element\Email) : ?>
            <div class="row clearfix">
                <?php //echo ($element->getLabel())? $this->formLabel($element) . ' ' . $requiredContent : ''; ?>
                <div class="col-md-7">
                    <?php echo $this->formEmail($element) ?>
                    <?php echo $this->formElementErrors($element) ?>
                </div>
            </div>
        <?php elseif ($element instanceof Zend\Form\Element\Radio) : ?>
            <div class="row clearfix check-el">
                <?php echo ($element->getLabel())? $this->formLabel($element) . ' ' . $requiredContent : ''; ?>
                <div class="row clearfix">
                    <div class="col-md-12">
                        <?php echo $this->formRadio($element) ?>
                        <?php echo $this->formElementErrors($element) ?>
                     </div>
                    <div class="comm">
                        <?php echo $this->translate('À l’occasion de chaque envoi vous aurez la possibilité de mettre fin à toute communication.')?>
                    </div>
                </div>
            </div>
        <?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox) : ?>
            <div class="requires">
                * <?php echo $this->translate('champs obligatoires')?>
            </div>
            <div class="row clearfix check-el">
                <?php echo ($element->getLabel())? $this->formLabel($element) . ' ' . $requiredContent : ''; ?>
                <div class="col-md-12">
                    <?php echo $this->formMultiCheckbox($element) ?>
                    <?php echo $this->formElementErrors($element) ?>
                 </div>
            </div>
        <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
            <div class=" clearfix">
                    <?php echo ($element->getLabel()) ? $this->formLabel($element) . ' ' . $requiredContent : ''; ?>
                    <div class="col-md-7">
                        <?php
                        echo $this->formTextarea($element);
                        ?>
                        <?php echo $this->formElementErrors($element) ?>
                    </div>
                   <div class="text-right col-md-11">
                       <span class="character-left"></span> 
                       <?php echo $this->translate('remaining characters'); ?>
                   </div>
             </div>
        <?php endif;?>
    <?php endforeach;?> 


    <?php echo $this->form()->closeTag() ?>
</div>

<div class="mentions hidden-sm hidden-md hidden-lg">
    <?php echo $this->translate('Les données personnelles que vous nous communiquez sont indispensables au traitement de votre demande mais vont également être utilisées à des fins d\'enquêtes ou d\'information sur les nouveaux produits ainsi que les offres du moment. Les destinataires des données sont la société Fiat France et son réseau commercial. En vous inscrivant vous acceptez d\'être contacté(e) ultérieurement. Conformément à la loi " informatique et libertés " du 6 janvier 1978 modifiée en 2004, vous bénéficiez d\'un droit d\'accès et de rectification aux informations vous concernant que vous pouvez exercer en vous adressant à Fiat France - Relation Clientèle - 6, rue Nicolas Copernic - 78190 Trappes.
Si vous ne souhaitez pas que vos données soient utilisées à des fins de prospection, veuillez cochez la case ci-contre')?>
</div>

<div class="center">
    <button type="submit" name="submitPost" value="" class="button" id="register-submit">
        <?php echo $this->translate('Suivant'); ?>
    </button>
</div>

<div class="mentions hidden-xs">
    <?php echo $this->translate('Les données personnelles que vous nous communiquez sont indispensables au traitement de votre demande mais vont également être utilisées à des fins d\'enquêtes ou d\'information sur les nouveaux produits ainsi que les offres du moment. Les destinataires des données sont la société Fiat France et son réseau commercial. En vous inscrivant vous acceptez d\'être contacté(e) ultérieurement. Conformément à la loi " informatique et libertés " du 6 janvier 1978 modifiée en 2004, vous bénéficiez d\'un droit d\'accès et de rectification aux informations vous concernant que vous pouvez exercer en vous adressant à Fiat France - Relation Clientèle - 6, rue Nicolas Copernic - 78190 Trappes.
Si vous ne souhaitez pas que vos données soient utilisées à des fins de prospection, veuillez cochez la case ci-contre')?>
</div>

<?php echo $this->partial('playground-game/partial/game-footer', array('game'=>$this->game, 'channel' => $this->channel));?>
<script type="text/javascript">
$('#register-submit').on('click', function(e) {
	$("ul.red").remove();
	var read = $('#read_the_rules');
	if (!read.prop('checked')) {
		displayError($('#read_the_rules').parent('label').parent('div'), "Vous devez accepter le règlement du jeu");
		e.preventDefault();
		return false;
	}

	if (!$('form input[name="nom"]').val()) {
		displayError($('form input[name="nom"]'), "Merci de remplir le champ");
		e.preventDefault();
		return false;
	}

	if (!$('form input[name="prenom"]').val()) {
		displayError($('form input[name="prenom"]'), "Merci de remplir le champ");
		e.preventDefault();
		return false;
	}
	
	var success = veriform($('form input[name="email"]'));
	if (!success) {
    	e.preventDefault();
    	return false;
	}
	if ($('form input[name="email"]').val() != $('form input[name="email_confirm"]').val()) {
    	displayError($('form input[name="email_confirm"]'), "Les emails doivent correspondre");
    	e.preventDefault();
    	return false;
	}
	if ($('input[name="opt_in"]:checked').val() == undefined) {
		displayError($('input[name="opt_in"]:eq(0)').parent('label').parent('div'), "Souhaitez-vous recevoir des actualités par email de la part de ALFA ROMEO");
		e.preventDefault();
		return false;
	}
	$('#zone_perso').children('form').submit();
});
var displayError = function(field, error) {
   if(field && error) {
	   $("<ul class=\"text-left red\"><li>"+error+"</li></ul>").insertAfter(field);
    }
}
var veriform = function(field) {
	var re = /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i;
    if(field.val() == '' || !re.test(field.val())){
      displayError(field, 'Merci de saisir un email valide');
      return false;
    }
    return true;
}
</script>
<!-- Sophus3 tag starts-->
<script type="text/javascript" language="JavaScript">
s3_page_alias="/promo/alfie/keepmeinformed/data_capture/";
</script>
<!-- Sophus3 tag ends-->
