<?php $this->plugin('translate')->setTranslatorTextDomain('playgrounduser');// Pour le texte ?>
<!-- NEW USER -->
<div id="new-user" >
	<h2>
	    <?php echo $this->translate('login or register'); ?>
	</h2>
	<!-- login -->
	<div id="login-part" data-redirect="<?php  if($this->redirect) : echo $this->redirect; else : $this->url('frontend', array('channel' => $this->channel)); endif; ?>">
		<p>
		    <?php echo $this->translate('Already an account ?')?>
		</p>
		<?php if(!$this->zfcUserIdentity()): ?>
		    <?php echo $this->userLoginWidget(array(
		        'redirect' => ($this->redirect) ? $this->redirect : $this->url('frontend', array('channel' => $this->channel)),
		        'enableRegistration' => false,
		        'template' => 'playground-user/register/login.phtml'
    		)); ?>
		<?php endif;?>
		<div class="input-login-error"></div>
	</div>
	<?php
    if (!$this->enableRegistration) {
        print "Registration is disabled";
        return;
    }
    $form = $this->registerForm;
    $form->prepare();
    $form->setAttribute('method', 'post');
	$form->setAttribute('class', 'form-horizontal');

    ?>
	<!-- create account -->
    <h2>
        <?php echo $this->translate('Create an account')?>
    </h2>
    <div id="fb-connect" class="row">
        <p class="col-md-4">
            <?php echo $this->translate('Use Facebook connect')?>
        </p>
        <p class="col-md-8">
            <a href="<?php echo $this->url('frontend/zfcuser/register',array('socialnetwork' => 'facebook', 'channel' => $this->channel)) . ($this->redirect ? '?redirect='.$this->redirect : '');?>">
               <img src="<?php echo $this->frontendAssetPath('images/common/fb-connect.png') ?>" alt="Facebook Connect" />
            </a>
        </p>
    </div>

	<div id="register-form">
		<!-- start form -->
        <?php echo $this->form()->openTag($form) ?>
			<div class="form-group">
				<p class="col-md-4 mandatory control-label"><?php echo $form->get('title')->getLabel(); ?></p>
				<p class="col-md-4">
            <?php foreach ($form->get('title')->getValueOptions() as $key => $value) : ?>
                <label class="radio-inline">
                    <input type="radio" name="<?php echo $form->get('title')->getAttribute('name'); ?>"
                        <?php echo ($key == $form->get('optin')->getValue()) ? 'checked="checked"' : ''; ?> value="<?php echo $key; ?>" />
                    <?php echo $value; ?>
                </label>
            <?php endforeach; ?>
				</p>
			</div>
			<div class="form-group">
				<label class="col-md-4 control-label mandatory" for="<?php echo $form->get('lastname')->getAttribute('id') ?>">
				    <?php echo $form->get('lastname')->getLabel(); ?>
				</label>
				<div class="col-md-4">
					<?php echo $this->formInput($form->get('lastname')->setAttributes(array('class' => 'form-control'))) ?>
					<?php echo $this->formElementErrors($form->get('lastname')) ?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-md-4 control-label mandatory" for="<?php echo $form->get('firstname')->getAttribute('id') ?>">
				    <?php echo $form->get('firstname')->getLabel(); ?>
				</label>
				<div class="col-md-4">
					<?php echo $this->formInput($form->get('firstname')->setAttributes(array('class' => 'form-control'))) ?>
					<?php echo $this->formElementErrors($form->get('firstname')) ?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-md-4 control-label mandatory" for="<?php echo $form->get('email')->getAttribute('id') ?>">
				    <?php echo $form->get('email')->getLabel(); ?>
			    </label>
				<div class="col-md-4">
				    <?php echo $this->formInput($form->get('email')->setAttributes(array('class' => 'form-control'))) ?>
				    <?php echo $this->formElementErrors($form->get('email')) ?>
				</div>
			</div>
			<?php //I do hide these fields on Facebook registration ?>
			<?php if($form->has('password')):?>
			<div class="form-group">
				<label class="col-md-4 control-label mandatory" for="<?php echo $form->get('password')->getAttribute('id') ?>">
				    <?php echo $form->get('password')->getLabel(); ?>
                    <span class="annotation">
                        ( 6 caractères minimum )
                    </span>
				</label>
				<div class="col-md-4">
					<?php echo $this->formInput($form->get('password')->setAttributes(array('class' => 'form-control'))) ?>
					<?php echo $this->formElementErrors($form->get('password')) ?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-md-4 control-label mandatory" for="<?php echo $form->get('passwordVerify')->getAttribute('id') ?>">
				    <?php echo $form->get('passwordVerify')->getLabel(); ?>
				</label>
				<div class="col-md-4">
					<?php echo $this->formInput($form->get('passwordVerify')->setAttributes(array('class' => 'form-control'))) ?>
					<?php echo $this->formElementErrors($form->get('passwordVerify')) ?>
				</div>
			</div>
			<?php endif;?>
			<div class="form-group">
				<label class="col-md-4 control-label mandatory" for="<?php echo $form->get('dob')->getAttribute('id') ?>">
				   <?php echo $form->get('dob')->getLabel(); ?>
			    </label>
				<div class="col-md-4 register-select mobile">
					<?php echo $this->formDateTime($form->get('dob')->setAttributes(array('class' => 'form-control'))) ?>
					<?php echo $this->formElementErrors($form->get('dob')) ?>
				</div>
			</div>
			<div class="form-group">
				<label class="col-md-4 control-label mandatory" for="<?php echo $form->get('postalCode')->getAttribute('id') ?>">
				    <?php echo $form->get('postalCode')->getLabel(); ?>
				</label>
				<div id="wrapcp" class="col-md-4">
					<?php echo $this->formInput($form->get('postalCode')->setAttributes(array('class' => 'form-control'))) ?>
					<?php echo $this->formElementErrors($form->get('postalCode')) ?>
				</div>
			</div>
            <h2>
                <?php echo $this->translate('Inscrivez-vous aux newsletters :')?>
            </h2>
			<!-- opt-in -->
			<div class="form-group">
                <p class="col-md-4 control-label">
                    <span class="mandatory"><?php echo $form->get('optin')->getLabel(); ?></span><br />
                    <span class="annotation"><?php echo $this->translate('(nouveaux jeux-concours, bons plans, invitations VIP...)')?></span>
                </p>
                <p class="col-md-4">
            <?php foreach ($form->get('optin')->getValueOptions() as $key => $value) : ?>
                <label class="radio-inline">
                    <input type="radio" name="<?php echo $form->get('optin')->getAttribute('name'); ?>"
                        <?php echo ($key == $form->get('optin')->getValue()) ? 'checked="checked"' : ''; ?> value="<?php echo $key; ?>" />
                    <?php echo $value; ?>
                </label>
            <?php endforeach; ?>
                </p>
			</div>
			<div class="form-group">
                <p class="col-md-4 control-label">
                    <span class="mandatory"><?php echo $form->get('optinPartner')->getLabel(); ?></span><br />
                    <span class="annotation"><?php echo $this->translate('(réductions, bons plans...)')?></span>
                </p>
                <p class="col-md-4">
            <?php foreach ($form->get('optin')->getValueOptions() as $key => $value) : ?>
                <label class="radio-inline">
                    <input type="radio" name="<?php echo $form->get('optinPartner')->getAttribute('name'); ?>"
                        <?php echo ($key == $form->get('optinPartner')->getValue()) ? 'checked="checked"' : ''; ?> value="<?php echo $key; ?>" />
                    <?php echo $value; ?>
                </label>
            <?php endforeach; ?>
                </p>
			</div>
			<div class="form-group">
				<p class="col-md-offset-4">
					<?php echo $this->formButton($form->get('submit')->setAttributes(array('class' => 'btn btn-default'))) ?>
				</p>
			</div>
			<?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
            <?php endif ?>
        <?php echo $this->form()->closeTag() ?>
		<!-- end form -->
	</div>
	<p id="annotation">
	    <?php echo $this->translate('* champs obligatoires')?>
	</p>
</div>
<!-- END NEW USER -->