<tr class="light">
    <td><?php echo $this->translate('Nb de membres parrainés'); ?></td>
    <td><?php echo number_format($this->sponsoredMembers, 0, ' ', ' ') ?></td>
    <td></td>
    <td></td>
</tr>
<tr>
    <td><?php echo $this->translate('Nb de partages totaux'); ?></td>
    <td><?php echo number_format($this->shares, 0, ' ', ' ') ?></td>
    <td></td>
    <td></td>
</tr>
<tr class="light">
    <td><?php echo $this->translate('Partage sur son profil'); ?></td>
    <td><?php echo number_format($this->profilShares, 0, ' ', ' ') ?></td>
    <td></td>
    <td></td>
</tr>
<tr height="50">
    <td></td>
    <td></td>
    <td></td>
    <td></td>
</tr>
<tr class="light">
    <td><?php echo $this->translate('Nb d\'invitations FB'); ?></td>
    <td><?php echo number_format($this->fbInvit, 0, ' ', ' ') ?></td>
    <td></td>
    <td></td>
</tr>
<tr>
    <td><?php echo $this->translate('Nb d\'invitations Tw'); ?></td>
    <td><?php echo number_format($this->twInvit, 0, ' ', ' ') ?></td>
    <td></td>
    <td></td>
</tr>
<tr class="light">
    <td><?php echo $this->translate('Nb d\'invitations G+'); ?></td>
    <td><?php echo number_format($this->glInvit, 0, ' ', ' ') ?></td>
    <td></td>
    <td></td>
</tr>
<tr>
    <td><?php echo $this->translate('Nb d\'invitations email'); ?></td>
    <td><?php echo number_format($this->mailInvit, 0, ' ', ' ') ?></td>
    <td></td>
    <td></td>
</tr>