<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 4.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>La Halle & Toys'R'us</title>
	<style type="text/css">
	</style>
</head>
<body bgcolor="#ffffff">

	<table width="100%" cellpadding="0" cellspacing="5" border="0" bgcolor="#ffffff">
		<tbody>
		<tr>
			<td align="center" >
				<table width="640" height="600" cellpadding="0" cellspacing="0" border="0" background="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/background.jpg">
					<tbody>
					<tr>

						<td width="557" align="center" style="font-size:0;padding:0;vertical-align:top"> 
							<table width="557" height="580" cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff">
								<tbody>
									<tr>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/sm1.jpg" alt="spiderman" border="0" width="120" height="60" />
										</td>
										<td width="317" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/header.jpg" alt="28 aout 11 septembre" border="0" width="317" height="60" />
										</td>
										<td width="120" height="60" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/hellokitty1.jpg" alt="hellokitty" border="0" width="120" height="60" />
										</td>
									</tr>

									<tr>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/sm2.jpg" alt="spiderman" border="0" width="120" height="44" />
										</td>
										<td width="317" align="center" height="44" style="font-size:0;padding:0;">
											<font face="Georgia" size="0" color="#000000" style=" font-size:16px; line-height:17px; font-weight:bold;">
												<?php if($this->zfcUserIdentity()):?>
												    <?php echo htmlentities($this->zfcUserIdentity()->getFirstname() . ' ' . $this->zfcUserIdentity()->getLastname(), ENT_QUOTES, "UTF-8") ?> vous invite à jouer au 
												<?php else: ?>
												    On vous invite à jouer au
												<?php endif; ?>
											</font>
										</td>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/hellokitty2.jpg" alt="hellokitty" border="0" width="120" height="44" />
										</td>
									</tr>



									<tr>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/jeuconcours1.jpg" alt="jeu concours" border="0" width="120" height="72" />
										</td>
										<td width="317" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/jeuconcours2.jpg" alt="jeu concours" border="0" width="317" height="72" />
										</td>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/jeuconcours3.jpg" alt="jeu concours" border="0" width="120" height="72" />
										</td>
									</tr>

									<tr>
										<td width="120" height="17" style="font-size:0;padding:0;">&nbsp;</td>
										<td width="317" height="17" style="font-size:0;padding:0;">&nbsp;</td>
										<td width="120" height="17" style="font-size:0;padding:0;">&nbsp;</td>
									</tr>

									<tr>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/tentez1.jpg" alt="tentez gagnez" border="0" width="120" height="69" />
										</td>
										<td width="317" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/tentez2.jpg" alt="tentez gagnez" border="0" width="317" height="69" />
										</td>
										<td width="120" height="69" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/tentez3.jpg" alt="tentez gagnez" border="0" width="120" height="69" />
										</td>
									</tr>

									<tr>
										<td width="120" style="font-size:0;padding:0;">&nbsp;</td>
										<td width="317" height="99" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/jouets1.jpg" alt="jouets" border="0" width="317" height="99" />
										</td>
										<td width="120" style="font-size:0;padding:0;">&nbsp;</td>
									</tr>

									<tr>
										<td width="120" style="font-size:0;padding:0;">&nbsp;</td>
										<td width="317" height="31" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/jouets2.jpg" alt="jouets" border="0" width="317" height="31" />
										</td>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/violetta0.jpg" alt="violetta" border="0" width="120" height="31" />
										</td>
									</tr>

									<tr>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/ca1.jpg" alt="captain america" border="0" width="120" height="52" />
										</td>
										<td width="317" height="52" style="font-size:0;padding:0;">
											<a href=""><img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/jouets3.jpg" alt="jouets" border="0" width="317" height="52" /></a>
										</td>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/violetta1.jpg" alt="violetta" border="0" width="120" height="52" />
										</td>
									</tr>

									<tr>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/ca2.jpg" alt="captain america" border="0" width="120" height="17" />
										</td>
										<td width="317" height="17" style="font-size:0;padding:0 30px;">
											<a href="http://www.lahalle.com/enfant/vos-heros-de-la-rentree" target="_blank"><img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/lahalle.jpg" alt="wwW.lahalle.com" border="0" width="98" height="17" /></a>
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/et.jpg" alt="dates" border="0" width="26" height="17" />
											<a href="http://www.toysrus.fr/" target="_blank"><img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/toysrus.jpg" alt="www.toysrus.fr" border="0" width="132" height="17" /></a>
										</td>
										<td width="120" height="17" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/violetta2.jpg" alt="violetta" border="0" width="120" height="17" />
										</td>
									</tr>

									<tr>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/ca3.jpg" alt="captain america" border="0" width="120" height="27" />
										</td>
										<td width="317" height="27" style="font-size:0;padding:0;">&nbsp;</td>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/violetta3.jpg" alt="violetta" border="0" width="120" height="27" />
										</td>
									</tr>

									<tr>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/ca4.jpg" alt="captain america" border="0" width="120" height="68" />
										</td>
										<td width="250" style="font-size:0;padding:0 33px;">
										<?php $gameclasstype = str_replace('/', '', $this->url('frontend/' . $this->game->getClassType(), array('channel' => $this->channel))); ?>
											<a href="<?php echo $this->skinUrl . '/' . $gameclasstype . '/' . $this->game->getIdentifier();?>?key=<?php echo $this->secretKey ?>"><img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/jouer.jpg" alt="jouer" border="0" width="250" height="68" /></a>
										</td>
										<td width="120" height="68" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/violetta4.jpg" alt="violetta" border="0" width="120" height="68" />
										</td>
									</tr>

									<tr>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/ca5.jpg" alt="captain america" border="0" width="120" height="23" />
										</td>
										<td width="317" height="23" style="font-size:0;padding:0;">&nbsp;</td>
										<td width="120" style="font-size:0;padding:0;">
											<img src="<?php echo $this->serverUrl(); ?>/frontend/images/lahalle/emailing1/violetta5.jpg" alt="violetta" border="0" width="120" height="23" />
										</td>
									</tr>

								</tbody>
							</table>
						</td>
					</tr>
				</tbody>
				</table>	
			</td>
		</tr>
	</tbody>
	</table>

</body>
</html>
